# Generated by Django 4.2.7 on 2024-01-22 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Avatares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatarimg',
            name='src_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares/'),
        ),
        migrations.AlterField(
            model_name='avatarimg',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
