# Generated by Django 4.2.7 on 2024-01-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avatares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='array_colores',
            field=models.CharField(max_length=900),
        ),
    ]
