# Generated by Django 4.2.7 on 2024-01-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Avatares', '0002_alter_avatarimg_src_imagen_alter_avatarimg_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
