# Generated by Django 4.2.7 on 2024-01-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0002_amistad_notificacion_seguimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amistad',
            name='par_amigos',
        ),
        migrations.AddField(
            model_name='amistad',
            name='id_usuario_a',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amistad',
            name='id_usuario_b',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
