# Generated by Django 4.2.7 on 2024-01-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0003_remove_amistad_par_amigos_amistad_id_usuario_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='username_receptor',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='id_receptor',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
