# Generated by Django 4.2.7 on 2024-01-17 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0005_notificacion_id_emisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
