# Generated by Django 4.2.7 on 2024-01-17 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0007_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
