# Generated by Django 4.2.7 on 2024-01-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0009_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='post_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
